name: thermal
description: Flutter plugin for accessing the device's thermal state.
repository: https://github.com/muxable/flutter_thermal
version: 1.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.muxable.flutter.thermal
        pluginClass: ThermalPlugin
      ios:
        pluginClass: ThermalPlugin
